spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/mall
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #show_sql: true #sout으로 sql이 찍힘
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug #debug로 sql이 찍힘
    org.hibernate.type: trace